# Generated by Django 3.2.7 on 2022-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите имя автора', null=True, verbose_name='Дата рождения автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Введите имя автора', null=True, verbose_name='Дата смерти автора'),
        ),
    ]
