# Generated by Django 3.2.7 on 2022-11-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221113_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Введите дату смерти', null=True, verbose_name='Дата смерти автора'),
        ),
    ]
